export const API_ERROR_CODE = {
  ACTIVE_SUBSCRIPTION_REQUIRED: "ACTIVE_SUBSCRIPTION_REQUIRED",
  LESSON_NOT_COMPLETED: "LESSON_NOT_COMPLETED",
  TEST_TIME_LIMIT_EXCEEDED: "TEST_TIME_LIMIT_EXCEEDED",
  TEST_ATTEMPTS_LIMIT_REACHED: "TEST_ATTEMPTS_LIMIT_REACHED",
  INVALID_RESET_TOKEN: "INVALID_RESET_TOKEN",
  TOKEN_VERSION_MISMATCH: "TOKEN_VERSION_MISMATCH",
} as const;

export type ApiErrorCode = (typeof API_ERROR_CODE)[keyof typeof API_ERROR_CODE];
